const PROJECT_STATUS = require('./projectStatus');

const STATUS_TRANSITIONS = {
	[PROJECT_STATUS.ACTIVE]: [
		PROJECT_STATUS.ON_HOLD,
		PROJECT_STATUS.COMPLETED
	],

	[PROJECT_STATUS.ON_HOLD]: [
		PROJECT_STATUS.ACTIVE,
		PROJECT_STATUS.COMPLETED
	],

	[PROJECT_STATUS.COMPLETED]: []
};

module.exports = STATUS_TRANSITIONS;
